### ISSUE TITLE
Launcher Crash [Fabric 1.14.3-02 version]

### ISSUE THREAD

**Issue by princessbinas** [Markus23/mybrightness#6]
After hitting play, the game crashes to the launcher.

[crash-2020-06-09_14.53.23-client.txt](https://github.com/Markus23/mybrightness/files/4754521/crash-2020-06-09_14.53.23-client.txt)

**Comment by amnotbananaama** [comment]
Do you have [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) in your `mods` folder? MyBrightness requires it.

**Comment by Markus23** [comment]
thx
